Feat/fr0 14 quick transcribe
workshopapps/grammarcheckerai.web pull request #40
Opened 2022-11-19 16:23 UTC by adedotxn

2022-11-19 17:15 UTC, OkoloJohnbosco requested changes
Please check all this. Thanks

2022-11-19 17:15 UTC, OkoloJohnbosco commented on packages/web/src/components/Audio/SentAudio.jsx
> +import { useState, useEffect } from 'react';
Are there extra files in the Audio component folder?? The convention for naming components is 
Audio - index.jsx
           -index.module.css
           
Please readjust

2022-11-19 17:15 UTC, OkoloJohnbosco commented on packages/web/src/components/Loaders/LoadingDots.jsx
> +import styles from './LoadingDots.module.css';
change this from LoadingDots.jsx to index.jsx

2022-11-19 17:15 UTC, OkoloJohnbosco commented on packages/web/src/components/Loaders/LoadingDots.module.css
> +.circle_one {
change this from LoadingDots.module.css to index.module.css

2022-11-19 17:32 UTC, adedotxn commented on packages/web/src/components/Audio/SentAudio.jsx
> +import { useState, useEffect } from 'react';
No, there are no extra files
alright

2022-11-19 17:33 UTC, adedotxn commented on packages/web/src/components/Audio/SentAudio.jsx
> +import { useState, useEffect } from 'react';
I will create a new PR right now

2022-11-19 17:37 UTC, adedotxn commented
@OkoloJohnbosco I have made the changes, I believe this PR will be automatically updated with the changes?

2022-11-19 21:45 UTC, adedotxn commented
@OkoloJohnbosco  there was someone's file that had a lot of errors -- linting errors, using class instead of className and using mapping over an array that's not even in the file, I had to make updates to that file because it made me unable to make commits or even push after pulling

I have no idea how the file was able to be commited or merged but it was.

I hope these changes do not affect other files

2022-11-20 08:00 UTC, OkoloJohnbosco commented
> @OkoloJohnbosco there was someone's file that had a lot of errors -- linting errors, using class instead of className and using mapping over an array that's not even in the file, I had to make updates to that file because it made me unable to make commits or even push after pulling
> 
> I have no idea how the file was able to be commited or merged but it was.
> 
> I hope these changes do not affect other files

Try pulling again

2022-11-21 02:42 UTC, merged

2022-11-21 19:59 UTC, onifs10 commented
@adedotxn pls can you add what page you implemented and link to the figma file to the description, Thanks

2022-11-21 20:24 UTC, adedotxn commented
> @adedotxn pls can you add what page/feature you implemented and link to the figma file to the description, Thanks

@onifs10 I have added these to the description

2022-11-21 20:30 UTC, onifs10 commented
@adedotxn, i honestly cant see any thing implemented on this page . 

even the import icon is in the wrong place 

![image](https://user-images.githubusercontent.com/48095055/203152433-1e8e5296-06c5-4379-84a6-362067ea0774.png)

2022-11-21 20:36 UTC, adedotxn commented
> @adedotxn, i honestly cant see any thing implemented on this page . 
> 
> even the import icon is in the wrong place 
> 
> ![image](https://user-images.githubusercontent.com/48095055/203152433-1e8e5296-06c5-4379-84a6-362067ea0774.png)
> 

The design was just adjusted yesterday. When I built it, that was what was there and submission time was already too close for me to start rebuilding/adjusting ..and the icon works for importing audio

I can't do much because I need an API to work with for the conversation flow to make even sense

Also, if the sidebars is affecting it (in mobile view), that was not my component to build, I had to resist touching it

2022-11-21 20:37 UTC, onifs10 commented
> > @adedotxn, i honestly cant see any thing implemented on this page .
> > even the import icon is in the wrong place
> > ![image](https://user-images.githubusercontent.com/48095055/203152433-1e8e5296-06c5-4379-84a6-362067ea0774.png)
> 
> The design was just adjusted yesterday. When I built it, that was what was there and submission time was already too close for me to start rebuilding/adjusting ..and the icon works for importing audio
> 
> I can't do much because I need an API to work with for the conversation flow to make even sense
> 
> Also, if the sidebars is affecting it (in mobile view), that was not my component to build, I had to resist touching it

alright